export const PRAXIS_PRODUCT_VERSION = '0.2.0' as const
export const PROTOCOL_VERSION = 1 as const
export const SUPPORTED_PROTOCOL_VERSIONS = [PROTOCOL_VERSION] as const

export const RUNTIME_METHODS = [
  'initialize',
  'events.subscribe',
  'auth.status',
  'auth.login',
  'auth.logout',
  'models.list',
  'settings.get',
  'settings.model.set',
  'runtime.doctor',
  'commands.list',
  'commands.invoke',
  'plugin.install',
  'plugin.list',
  'plugin.inspect',
  'plugin.enable',
  'plugin.disable',
  'plugin.permissions',
  'plugin.doctor',
  'plugin.update',
  'plugin.rollback',
  'plugin.uninstall',
  'resource.list',
  'resource.inspect',
  'resource.enable',
  'resource.disable',
  'session.create',
  'session.list',
  'session.search',
  'session.inspect',
  'session.resume',
  'session.rename',
  'session.configure',
  'session.close',
  'session.delete',
  'session.export',
  'session.transcript',
  'session.fork',
  'session.branch',
  'session.compact',
  'session.plan',
  'workflow.get',
  'workflow.list',
  'workflow.events',
  'workflow.signal',
  'workflow.pause',
  'workflow.resume',
  'workflow.cancel',
  'workflow.terminate',
  'workflow.human-tasks.list',
  'workflow.human-task.resolve',
  'workflow.retry-node',
  'workflow.resolve-unknown',
  'artifacts.list',
  'session.prompt',
  'session.follow_up',
  'session.steer',
  'session.abort',
  'trace.export',
  'permission.decide',
  'shutdown',
] as const

export type RuntimeMethod = (typeof RUNTIME_METHODS)[number]

export const SESSION_EVENT_TYPES = [
  'runtime_ready',
  'auth_login_action',
  'auth_status_changed',
  'runtime_warning',
  'prompt_started',
  'thinking_delta',
  'text_delta',
  'tool_planning',
  'permission_request',
  'tool_start',
  'tool_update',
  'tool_end',
  'steer_queued',
  'steer_applied',
  'message_committed',
  'prompt_completed',
  'prompt_failed',
  'prompt_aborted',
  'supervisor_update',
  'workflow_update',
] as const
